#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

##
## Configuration Variables
##

# The build configuration to use.
if [ -z "$XCCONFIGURATION" ]
then
    XCCONFIGURATION="Release"
fi

# The workspace to build.
#
# If not set and no workspace is found, the -workspace flag will not be passed
# to xcodebuild.
if [ -z "$XCWORKSPACE" ]
then
    XCWORKSPACE=$(ls -d *.xcworkspace | head -n 1)
fi

# A bootstrap script to run before building.
#
# If this file does not exist, it is not considered an error.
BOOTSTRAP="$SCRIPT_DIR/bootstrap"

##
## Build Process
##

if [ -z "$*" ]
then
    # lol recursive shell script
    xcodebuild -list | awk -f "$SCRIPT_DIR/targets.awk" | xargs "$SCRIPT_DIR/cibuild"
    exit $?
fi

if [ -f "$BOOTSTRAP" ]
then
    echo "*** Bootstrapping…"
    bash "$BOOTSTRAP"
fi

echo "*** The following targets will be built:"

for target in "$@"
do
    echo "$target"
done

echo "*** Cleaning all targets…"
xcodebuild -alltargets clean

build_scheme ()
{
    local scheme=$1
    local action=$2

    if [ -n "$XCWORKSPACE" ]
    then
        xcodebuild -workspace "$XCWORKSPACE" -scheme "$scheme" -configuration "$XCCONFIGURATION" "$action"
    else
        xcodebuild -scheme "$scheme" -configuration "$XCCONFIGURATION" "$action"
    fi

    local status=$?

    return $status
}

test_or_build ()
{
    local scheme=$1

    build_scheme "$scheme" "test" 2>&1 | awk -f "$SCRIPT_DIR/xcodebuild.awk"

    local awkstatus=$?
    local xcstatus=${PIPESTATUS[0]}

    if [ "$awkstatus" -eq "1" ]
    then
        return $awkstatus
    fi

    if [ "$xcstatus" -eq "65" -o "$awkstatus" -eq "2" ]
    then
        # This probably means the 'test' action isn't supported. Try again with
        # 'build'.
        build_scheme "$scheme" "build"
        xcstatus=$?
    fi

    if [ "$xcstatus" -eq "65" ]
    then
        # This probably means that there's no scheme by that name. Give up.
        echo "*** Error building scheme $scheme -- perhaps it doesn't exist"
    fi

    return $xcstatus
}

echo "*** Building…"

for scheme in "$@"
do
    test_or_build "$scheme" || exit $?
done
