#!/bin/bash

if [[ -z "$1" ]]; then
	echo "Please specify a version tag."
	exit
fi

PRERELEASE_STRIPPED=$(echo "$1" | perl -0777 -ne '/([0-9]+)\.([0-9]+)\.([0-9]+)(-.*)?/ and print "$1.$2.$3"')

if [[ -z "$PRERELEASE_STRIPPED" ]]; then
	echo "The version tag is not semver compliant."
	exit
fi

CURRENT_TAG=$(perl -0777 -ne '/s.version([\s]+)=([\s]+)"(.+)"/ and print $3' *.podspec)
echo "Current tag: $CURRENT_TAG"

perl -0777 -i -pe 's/s.version([\s]+)=([\s]+)"'${CURRENT_TAG}'"/s.version$1=$2"'${1}'"/' *.podspec
perl -0777 -i -pe 's/g>'${CURRENT_TAG}'<\/str/g>'${PRERELEASE_STRIPPED}'<\/str/' */Info.plist
perl -0777 -i -pe 's/g>'${CURRENT_TAG}'<\/str/g>'${PRERELEASE_STRIPPED}'<\/str/' */*/Info.plist
sed -i '' '3i\
\
# '${1} CHANGELOG.md

